# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "ahci"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "dm-snapshot"
    "cryptd"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    # Modify this to the name of the root logical volume (name you used in mkfs.ext4)
    {
      device = "/dev/disk/by-label/NixOS-Root"; # <- Change this
      fsType = "ext4";
    };

  # Modify this to the name of the encrypted partition (name you used in cryptsetup luksFormat)
  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-label/NixOS-Encrypted"; # If you followed the guide with the same names, or else change "NixOS-Encrypted" to whetever you named it

  # Modify this to the name of the unencrypted boot partition (name you used in mkfs.fat)
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/NixOS-Boot"; # <- Change this
    fsType = "vfat";
  };
  # Modify this to the name of the swap logical volume (name you used in mkswap)
  swapDevices = [ { device = "/dev/disk/by-label/NixOS-Swap"; } ]; # <- Change this

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
